title: Ángel
tagline: Mi portal personal
description: Sitio personal en GitHub Pages.
url: https://angelTomo9.github.io

include:
  - "apps/swissknife/_next"

defaults:
  - scope:
      path: ""
    values:
      layout: default

markdown: kramdown
