const partidos = [
    {
        "id":  537327,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_A",
        "utcDate":  "2026-06-11T19:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Mexico",
        "awayTeam":  "South Africa",
        "homeCrest":  "https://crests.football-data.org/769.svg",
        "awayCrest":  "https://crests.football-data.org/9396.svg",
        "winnerReal":  null
    },
    {
        "id":  537328,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_A",
        "utcDate":  "2026-06-12T02:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "South Korea",
        "awayTeam":  "Czechia",
        "homeCrest":  "https://crests.football-data.org/772.png",
        "awayCrest":  "https://crests.football-data.org/798.svg",
        "winnerReal":  null
    },
    {
        "id":  537333,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_B",
        "utcDate":  "2026-06-12T19:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Canada",
        "awayTeam":  "Bosnia-Herzegovina",
        "homeCrest":  "https://crests.football-data.org/canada.svg",
        "awayCrest":  "https://crests.football-data.org/bosnia.svg",
        "winnerReal":  null
    },
    {
        "id":  537345,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_D",
        "utcDate":  "2026-06-13T01:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "United States",
        "awayTeam":  "Paraguay",
        "homeCrest":  "https://crests.football-data.org/usa.svg",
        "awayCrest":  "https://crests.football-data.org/761.svg",
        "winnerReal":  null
    },
    {
        "id":  537334,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_B",
        "utcDate":  "2026-06-13T19:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Qatar",
        "awayTeam":  "Switzerland",
        "homeCrest":  "https://crests.football-data.org/8030.svg",
        "awayCrest":  "https://crests.football-data.org/788.svg",
        "winnerReal":  null
    },
    {
        "id":  537339,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_C",
        "utcDate":  "2026-06-13T22:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Brazil",
        "awayTeam":  "Morocco",
        "homeCrest":  "https://crests.football-data.org/764.svg",
        "awayCrest":  "https://crests.football-data.org/morocco.svg",
        "winnerReal":  null
    },
    {
        "id":  537340,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_C",
        "utcDate":  "2026-06-14T01:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Haiti",
        "awayTeam":  "Scotland",
        "homeCrest":  "https://crests.football-data.org/haiti.svg",
        "awayCrest":  "https://crests.football-data.org/814.svg",
        "winnerReal":  null
    },
    {
        "id":  537346,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_D",
        "utcDate":  "2026-06-14T04:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Australia",
        "awayTeam":  "Turkey",
        "homeCrest":  "https://crests.football-data.org/779.svg",
        "awayCrest":  "https://crests.football-data.org/803.svg",
        "winnerReal":  null
    },
    {
        "id":  537351,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_E",
        "utcDate":  "2026-06-14T17:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Germany",
        "awayTeam":  "Curaçao",
        "homeCrest":  "https://crests.football-data.org/759.svg",
        "awayCrest":  "https://crests.football-data.org/curacao.svg",
        "winnerReal":  null
    },
    {
        "id":  537357,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_F",
        "utcDate":  "2026-06-14T20:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Netherlands",
        "awayTeam":  "Japan",
        "homeCrest":  "https://crests.football-data.org/8601.svg",
        "awayCrest":  "https://crests.football-data.org/766.svg",
        "winnerReal":  null
    },
    {
        "id":  537352,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_E",
        "utcDate":  "2026-06-14T23:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Ivory Coast",
        "awayTeam":  "Ecuador",
        "homeCrest":  "https://crests.football-data.org/787.svg",
        "awayCrest":  "https://crests.football-data.org/791.svg",
        "winnerReal":  null
    },
    {
        "id":  537358,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_F",
        "utcDate":  "2026-06-15T02:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Sweden",
        "awayTeam":  "Tunisia",
        "homeCrest":  "https://crests.football-data.org/792.svg",
        "awayCrest":  "https://crests.football-data.org/tunisia.svg",
        "winnerReal":  null
    },
    {
        "id":  537369,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_H",
        "utcDate":  "2026-06-15T16:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Spain",
        "awayTeam":  "Cape Verde Islands",
        "homeCrest":  "https://crests.football-data.org/760.svg",
        "awayCrest":  "https://crests.football-data.org/cape_verde.svg",
        "winnerReal":  null
    },
    {
        "id":  537363,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_G",
        "utcDate":  "2026-06-15T19:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Belgium",
        "awayTeam":  "Egypt",
        "homeCrest":  "https://crests.football-data.org/805.svg",
        "awayCrest":  "https://crests.football-data.org/825.svg",
        "winnerReal":  null
    },
    {
        "id":  537370,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_H",
        "utcDate":  "2026-06-15T22:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Saudi Arabia",
        "awayTeam":  "Uruguay",
        "homeCrest":  "https://crests.football-data.org/saudi_arabia.svg",
        "awayCrest":  "https://crests.football-data.org/758.svg",
        "winnerReal":  null
    },
    {
        "id":  537364,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_G",
        "utcDate":  "2026-06-16T01:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Iran",
        "awayTeam":  "New Zealand",
        "homeCrest":  "https://crests.football-data.org/iran.svg",
        "awayCrest":  "https://crests.football-data.org/783.svg",
        "winnerReal":  null
    },
    {
        "id":  537391,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_I",
        "utcDate":  "2026-06-16T19:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "France",
        "awayTeam":  "Senegal",
        "homeCrest":  "https://crests.football-data.org/773.svg",
        "awayCrest":  "https://crests.football-data.org/senegal.svg",
        "winnerReal":  null
    },
    {
        "id":  537392,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_I",
        "utcDate":  "2026-06-16T22:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Iraq",
        "awayTeam":  "Norway",
        "homeCrest":  "https://crests.football-data.org/iraq.svg",
        "awayCrest":  "https://crests.football-data.org/813.svg",
        "winnerReal":  null
    },
    {
        "id":  537397,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_J",
        "utcDate":  "2026-06-17T01:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Argentina",
        "awayTeam":  "Algeria",
        "homeCrest":  "https://crests.football-data.org/762.png",
        "awayCrest":  "https://crests.football-data.org/algeria.svg",
        "winnerReal":  null
    },
    {
        "id":  537398,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_J",
        "utcDate":  "2026-06-17T04:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Austria",
        "awayTeam":  "Jordan",
        "homeCrest":  "https://crests.football-data.org/816.svg",
        "awayCrest":  "https://crests.football-data.org/8049.png",
        "winnerReal":  null
    },
    {
        "id":  537403,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_K",
        "utcDate":  "2026-06-17T17:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Portugal",
        "awayTeam":  "Congo DR",
        "homeCrest":  "https://crests.football-data.org/765.svg",
        "awayCrest":  "https://crests.football-data.org/congo_dr.svg",
        "winnerReal":  null
    },
    {
        "id":  537409,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_L",
        "utcDate":  "2026-06-17T20:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "England",
        "awayTeam":  "Croatia",
        "homeCrest":  "https://crests.football-data.org/770.svg",
        "awayCrest":  "https://crests.football-data.org/799.svg",
        "winnerReal":  null
    },
    {
        "id":  537410,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_L",
        "utcDate":  "2026-06-17T23:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Ghana",
        "awayTeam":  "Panama",
        "homeCrest":  "https://crests.football-data.org/ghana.svg",
        "awayCrest":  "https://crests.football-data.org/panama.svg",
        "winnerReal":  null
    },
    {
        "id":  537404,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_K",
        "utcDate":  "2026-06-18T02:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Uzbekistan",
        "awayTeam":  "Colombia",
        "homeCrest":  "https://crests.football-data.org/8070.png",
        "awayCrest":  "https://crests.football-data.org/818.svg",
        "winnerReal":  null
    },
    {
        "id":  537329,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_A",
        "utcDate":  "2026-06-18T16:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Czechia",
        "awayTeam":  "South Africa",
        "homeCrest":  "https://crests.football-data.org/798.svg",
        "awayCrest":  "https://crests.football-data.org/9396.svg",
        "winnerReal":  null
    },
    {
        "id":  537335,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_B",
        "utcDate":  "2026-06-18T19:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Switzerland",
        "awayTeam":  "Bosnia-Herzegovina",
        "homeCrest":  "https://crests.football-data.org/788.svg",
        "awayCrest":  "https://crests.football-data.org/bosnia.svg",
        "winnerReal":  null
    },
    {
        "id":  537336,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_B",
        "utcDate":  "2026-06-18T22:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Canada",
        "awayTeam":  "Qatar",
        "homeCrest":  "https://crests.football-data.org/canada.svg",
        "awayCrest":  "https://crests.football-data.org/8030.svg",
        "winnerReal":  null
    },
    {
        "id":  537330,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_A",
        "utcDate":  "2026-06-19T01:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Mexico",
        "awayTeam":  "South Korea",
        "homeCrest":  "https://crests.football-data.org/769.svg",
        "awayCrest":  "https://crests.football-data.org/772.png",
        "winnerReal":  null
    },
    {
        "id":  537348,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_D",
        "utcDate":  "2026-06-19T19:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "United States",
        "awayTeam":  "Australia",
        "homeCrest":  "https://crests.football-data.org/usa.svg",
        "awayCrest":  "https://crests.football-data.org/779.svg",
        "winnerReal":  null
    },
    {
        "id":  537342,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_C",
        "utcDate":  "2026-06-19T22:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Scotland",
        "awayTeam":  "Morocco",
        "homeCrest":  "https://crests.football-data.org/814.svg",
        "awayCrest":  "https://crests.football-data.org/morocco.svg",
        "winnerReal":  null
    },
    {
        "id":  537341,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_C",
        "utcDate":  "2026-06-20T00:30:00Z",
        "status":  "TIMED",
        "homeTeam":  "Brazil",
        "awayTeam":  "Haiti",
        "homeCrest":  "https://crests.football-data.org/764.svg",
        "awayCrest":  "https://crests.football-data.org/haiti.svg",
        "winnerReal":  null
    },
    {
        "id":  537347,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_D",
        "utcDate":  "2026-06-20T03:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Turkey",
        "awayTeam":  "Paraguay",
        "homeCrest":  "https://crests.football-data.org/803.svg",
        "awayCrest":  "https://crests.football-data.org/761.svg",
        "winnerReal":  null
    },
    {
        "id":  537359,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_F",
        "utcDate":  "2026-06-20T17:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Netherlands",
        "awayTeam":  "Sweden",
        "homeCrest":  "https://crests.football-data.org/8601.svg",
        "awayCrest":  "https://crests.football-data.org/792.svg",
        "winnerReal":  null
    },
    {
        "id":  537353,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_E",
        "utcDate":  "2026-06-20T20:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Germany",
        "awayTeam":  "Ivory Coast",
        "homeCrest":  "https://crests.football-data.org/759.svg",
        "awayCrest":  "https://crests.football-data.org/787.svg",
        "winnerReal":  null
    },
    {
        "id":  537354,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_E",
        "utcDate":  "2026-06-21T00:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Ecuador",
        "awayTeam":  "Curaçao",
        "homeCrest":  "https://crests.football-data.org/791.svg",
        "awayCrest":  "https://crests.football-data.org/curacao.svg",
        "winnerReal":  null
    },
    {
        "id":  537360,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_F",
        "utcDate":  "2026-06-21T04:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Tunisia",
        "awayTeam":  "Japan",
        "homeCrest":  "https://crests.football-data.org/tunisia.svg",
        "awayCrest":  "https://crests.football-data.org/766.svg",
        "winnerReal":  null
    },
    {
        "id":  537371,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_H",
        "utcDate":  "2026-06-21T16:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Spain",
        "awayTeam":  "Saudi Arabia",
        "homeCrest":  "https://crests.football-data.org/760.svg",
        "awayCrest":  "https://crests.football-data.org/saudi_arabia.svg",
        "winnerReal":  null
    },
    {
        "id":  537365,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_G",
        "utcDate":  "2026-06-21T19:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Belgium",
        "awayTeam":  "Iran",
        "homeCrest":  "https://crests.football-data.org/805.svg",
        "awayCrest":  "https://crests.football-data.org/iran.svg",
        "winnerReal":  null
    },
    {
        "id":  537372,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_H",
        "utcDate":  "2026-06-21T22:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Uruguay",
        "awayTeam":  "Cape Verde Islands",
        "homeCrest":  "https://crests.football-data.org/758.svg",
        "awayCrest":  "https://crests.football-data.org/cape_verde.svg",
        "winnerReal":  null
    },
    {
        "id":  537366,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_G",
        "utcDate":  "2026-06-22T01:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "New Zealand",
        "awayTeam":  "Egypt",
        "homeCrest":  "https://crests.football-data.org/783.svg",
        "awayCrest":  "https://crests.football-data.org/825.svg",
        "winnerReal":  null
    },
    {
        "id":  537399,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_J",
        "utcDate":  "2026-06-22T17:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Argentina",
        "awayTeam":  "Austria",
        "homeCrest":  "https://crests.football-data.org/762.png",
        "awayCrest":  "https://crests.football-data.org/816.svg",
        "winnerReal":  null
    },
    {
        "id":  537393,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_I",
        "utcDate":  "2026-06-22T21:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "France",
        "awayTeam":  "Iraq",
        "homeCrest":  "https://crests.football-data.org/773.svg",
        "awayCrest":  "https://crests.football-data.org/iraq.svg",
        "winnerReal":  null
    },
    {
        "id":  537394,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_I",
        "utcDate":  "2026-06-23T00:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Norway",
        "awayTeam":  "Senegal",
        "homeCrest":  "https://crests.football-data.org/813.svg",
        "awayCrest":  "https://crests.football-data.org/senegal.svg",
        "winnerReal":  null
    },
    {
        "id":  537400,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_J",
        "utcDate":  "2026-06-23T03:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Jordan",
        "awayTeam":  "Algeria",
        "homeCrest":  "https://crests.football-data.org/8049.png",
        "awayCrest":  "https://crests.football-data.org/algeria.svg",
        "winnerReal":  null
    },
    {
        "id":  537405,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_K",
        "utcDate":  "2026-06-23T17:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Portugal",
        "awayTeam":  "Uzbekistan",
        "homeCrest":  "https://crests.football-data.org/765.svg",
        "awayCrest":  "https://crests.football-data.org/8070.png",
        "winnerReal":  null
    },
    {
        "id":  537411,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_L",
        "utcDate":  "2026-06-23T20:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "England",
        "awayTeam":  "Ghana",
        "homeCrest":  "https://crests.football-data.org/770.svg",
        "awayCrest":  "https://crests.football-data.org/ghana.svg",
        "winnerReal":  null
    },
    {
        "id":  537412,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_L",
        "utcDate":  "2026-06-23T23:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Panama",
        "awayTeam":  "Croatia",
        "homeCrest":  "https://crests.football-data.org/panama.svg",
        "awayCrest":  "https://crests.football-data.org/799.svg",
        "winnerReal":  null
    },
    {
        "id":  537406,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_K",
        "utcDate":  "2026-06-24T02:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Colombia",
        "awayTeam":  "Congo DR",
        "homeCrest":  "https://crests.football-data.org/818.svg",
        "awayCrest":  "https://crests.football-data.org/congo_dr.svg",
        "winnerReal":  null
    },
    {
        "id":  537337,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_B",
        "utcDate":  "2026-06-24T19:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Switzerland",
        "awayTeam":  "Canada",
        "homeCrest":  "https://crests.football-data.org/788.svg",
        "awayCrest":  "https://crests.football-data.org/canada.svg",
        "winnerReal":  null
    },
    {
        "id":  537338,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_B",
        "utcDate":  "2026-06-24T19:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Bosnia-Herzegovina",
        "awayTeam":  "Qatar",
        "homeCrest":  "https://crests.football-data.org/bosnia.svg",
        "awayCrest":  "https://crests.football-data.org/8030.svg",
        "winnerReal":  null
    },
    {
        "id":  537344,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_C",
        "utcDate":  "2026-06-24T22:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Morocco",
        "awayTeam":  "Haiti",
        "homeCrest":  "https://crests.football-data.org/morocco.svg",
        "awayCrest":  "https://crests.football-data.org/haiti.svg",
        "winnerReal":  null
    },
    {
        "id":  537343,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_C",
        "utcDate":  "2026-06-24T22:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Scotland",
        "awayTeam":  "Brazil",
        "homeCrest":  "https://crests.football-data.org/814.svg",
        "awayCrest":  "https://crests.football-data.org/764.svg",
        "winnerReal":  null
    },
    {
        "id":  537331,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_A",
        "utcDate":  "2026-06-25T01:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Czechia",
        "awayTeam":  "Mexico",
        "homeCrest":  "https://crests.football-data.org/798.svg",
        "awayCrest":  "https://crests.football-data.org/769.svg",
        "winnerReal":  null
    },
    {
        "id":  537332,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_A",
        "utcDate":  "2026-06-25T01:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "South Africa",
        "awayTeam":  "South Korea",
        "homeCrest":  "https://crests.football-data.org/9396.svg",
        "awayCrest":  "https://crests.football-data.org/772.png",
        "winnerReal":  null
    },
    {
        "id":  537355,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_E",
        "utcDate":  "2026-06-25T20:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Ecuador",
        "awayTeam":  "Germany",
        "homeCrest":  "https://crests.football-data.org/791.svg",
        "awayCrest":  "https://crests.football-data.org/759.svg",
        "winnerReal":  null
    },
    {
        "id":  537356,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_E",
        "utcDate":  "2026-06-25T20:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Curaçao",
        "awayTeam":  "Ivory Coast",
        "homeCrest":  "https://crests.football-data.org/curacao.svg",
        "awayCrest":  "https://crests.football-data.org/787.svg",
        "winnerReal":  null
    },
    {
        "id":  537361,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_F",
        "utcDate":  "2026-06-25T23:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Tunisia",
        "awayTeam":  "Netherlands",
        "homeCrest":  "https://crests.football-data.org/tunisia.svg",
        "awayCrest":  "https://crests.football-data.org/8601.svg",
        "winnerReal":  null
    },
    {
        "id":  537362,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_F",
        "utcDate":  "2026-06-25T23:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Japan",
        "awayTeam":  "Sweden",
        "homeCrest":  "https://crests.football-data.org/766.svg",
        "awayCrest":  "https://crests.football-data.org/792.svg",
        "winnerReal":  null
    },
    {
        "id":  537349,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_D",
        "utcDate":  "2026-06-26T02:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Turkey",
        "awayTeam":  "United States",
        "homeCrest":  "https://crests.football-data.org/803.svg",
        "awayCrest":  "https://crests.football-data.org/usa.svg",
        "winnerReal":  null
    },
    {
        "id":  537350,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_D",
        "utcDate":  "2026-06-26T02:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Paraguay",
        "awayTeam":  "Australia",
        "homeCrest":  "https://crests.football-data.org/761.svg",
        "awayCrest":  "https://crests.football-data.org/779.svg",
        "winnerReal":  null
    },
    {
        "id":  537395,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_I",
        "utcDate":  "2026-06-26T19:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Norway",
        "awayTeam":  "France",
        "homeCrest":  "https://crests.football-data.org/813.svg",
        "awayCrest":  "https://crests.football-data.org/773.svg",
        "winnerReal":  null
    },
    {
        "id":  537396,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_I",
        "utcDate":  "2026-06-26T19:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Senegal",
        "awayTeam":  "Iraq",
        "homeCrest":  "https://crests.football-data.org/senegal.svg",
        "awayCrest":  "https://crests.football-data.org/iraq.svg",
        "winnerReal":  null
    },
    {
        "id":  537373,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_H",
        "utcDate":  "2026-06-27T00:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Uruguay",
        "awayTeam":  "Spain",
        "homeCrest":  "https://crests.football-data.org/758.svg",
        "awayCrest":  "https://crests.football-data.org/760.svg",
        "winnerReal":  null
    },
    {
        "id":  537374,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_H",
        "utcDate":  "2026-06-27T00:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Cape Verde Islands",
        "awayTeam":  "Saudi Arabia",
        "homeCrest":  "https://crests.football-data.org/cape_verde.svg",
        "awayCrest":  "https://crests.football-data.org/saudi_arabia.svg",
        "winnerReal":  null
    },
    {
        "id":  537367,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_G",
        "utcDate":  "2026-06-27T03:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "New Zealand",
        "awayTeam":  "Belgium",
        "homeCrest":  "https://crests.football-data.org/783.svg",
        "awayCrest":  "https://crests.football-data.org/805.svg",
        "winnerReal":  null
    },
    {
        "id":  537368,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_G",
        "utcDate":  "2026-06-27T03:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Egypt",
        "awayTeam":  "Iran",
        "homeCrest":  "https://crests.football-data.org/825.svg",
        "awayCrest":  "https://crests.football-data.org/iran.svg",
        "winnerReal":  null
    },
    {
        "id":  537413,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_L",
        "utcDate":  "2026-06-27T21:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Panama",
        "awayTeam":  "England",
        "homeCrest":  "https://crests.football-data.org/panama.svg",
        "awayCrest":  "https://crests.football-data.org/770.svg",
        "winnerReal":  null
    },
    {
        "id":  537414,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_L",
        "utcDate":  "2026-06-27T21:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Croatia",
        "awayTeam":  "Ghana",
        "homeCrest":  "https://crests.football-data.org/799.svg",
        "awayCrest":  "https://crests.football-data.org/ghana.svg",
        "winnerReal":  null
    },
    {
        "id":  537407,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_K",
        "utcDate":  "2026-06-27T23:30:00Z",
        "status":  "TIMED",
        "homeTeam":  "Colombia",
        "awayTeam":  "Portugal",
        "homeCrest":  "https://crests.football-data.org/818.svg",
        "awayCrest":  "https://crests.football-data.org/765.svg",
        "winnerReal":  null
    },
    {
        "id":  537408,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_K",
        "utcDate":  "2026-06-27T23:30:00Z",
        "status":  "TIMED",
        "homeTeam":  "Congo DR",
        "awayTeam":  "Uzbekistan",
        "homeCrest":  "https://crests.football-data.org/congo_dr.svg",
        "awayCrest":  "https://crests.football-data.org/8070.png",
        "winnerReal":  null
    },
    {
        "id":  537401,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_J",
        "utcDate":  "2026-06-28T02:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Jordan",
        "awayTeam":  "Argentina",
        "homeCrest":  "https://crests.football-data.org/8049.png",
        "awayCrest":  "https://crests.football-data.org/762.png",
        "winnerReal":  null
    },
    {
        "id":  537402,
        "stage":  "GROUP_STAGE",
        "group":  "GROUP_J",
        "utcDate":  "2026-06-28T02:00:00Z",
        "status":  "TIMED",
        "homeTeam":  "Algeria",
        "awayTeam":  "Austria",
        "homeCrest":  "https://crests.football-data.org/algeria.svg",
        "awayCrest":  "https://crests.football-data.org/816.svg",
        "winnerReal":  null
    }
]
;
